spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: ${DB_USER:postgres}
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mat_fit}
        password: ${DB_PASSWORD:12345}
    output:
        ansi:
            enabled: always
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
